In [ ]:
from google.colab import files
import os

# This will open a file picker dialog for you to select files from your local machine.
print("Please select a file to upload:")
uploaded = files.upload()

for filename in uploaded.keys():
  print(f'User uploaded file "{filename}" with length {len(uploaded[filename])} bytes')
  # Optionally, save the uploaded file to the current directory
  with open(filename, 'wb') as f:
    f.write(uploaded[filename])
  print(f'Saved file to {os.path.join(os.getcwd(), filename)}')

Please select a file to upload:

Saving Dataset.csv to Dataset.csv
User uploaded file "Dataset.csv" with length 416506 bytes
Saved file to /content/Dataset.csv

In [ ]:
import pandas as pd

df = pd.read_csv('Dataset.csv')
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [ ]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [ ]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [ ]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [ ]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [ ]:
df.columns = df.columns.str.upper()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'PURCHASE_AMOUNT_(USD)':'PURCHASE_AMOUNT'})

In [ ]:
labels = ['Young', 'Adult', 'Mid-age', 'Old']
df['AGE_GROUP'] = pd.qcut(df['AGE'], q=4, labels=labels)

In [ ]:
df[['AGE','AGE_GROUP']].head(11)

    AGE AGE_GROUP
0    55   Mid-age
1    19     Young
2    50   Mid-age
3    21     Young
4    45   Mid-age
5    46   Mid-age
6    63       Old
7    27     Young
8    26     Young
9    57   Mid-age
10   53   Mid-age

In [ ]:
frequency_mapping = {
    'Weekly': 7,
    'Fortnightly': 14,
    'Monthly': 30,
    'Quarterly': 90,
    'Every 3 Months': 90,
    'Bi-Weekly': 14,
    'Annually': 365
}
df['PURCHASE_FREQUENCY'] = df['FREQUENCY_OF_PURCHASES'].map(frequency_mapping)

In [ ]:
df[['AGE', 'AGE_GROUP', 'FREQUENCY_OF_PURCHASES', 'PURCHASE_FREQUENCY']].head(11)

    AGE AGE_GROUP FREQUENCY_OF_PURCHASES  PURCHASE_FREQUENCY
0    55   Mid-age            Fortnightly                  14
1    19     Young            Fortnightly                  14
2    50   Mid-age                 Weekly                   7
3    21     Young                 Weekly                   7
4    45   Mid-age               Annually                 365
5    46   Mid-age                 Weekly                   7
6    63       Old              Quarterly                  90
7    27     Young                 Weekly                   7
8    26     Young               Annually                 365
9    57   Mid-age              Quarterly                  90
10   53   Mid-age              Bi-Weekly                  14

In [ ]:
(df['DISCOUNT_APPLIED'] == df['PROMO_CODE_USED']).all()

np.True_

In [ ]:
df = df.drop('PROMO_CODE_USED', axis=1)

In [ ]:
df.columns

Index(['CUSTOMER_ID', 'AGE', 'GENDER', 'ITEM_PURCHASED', 'CATEGORY',
       'PURCHASE_AMOUNT', 'LOCATION', 'SIZE', 'COLOR', 'SEASON',
       'REVIEW_RATING', 'SUBSCRIPTION_STATUS', 'SHIPPING_TYPE',
       'DISCOUNT_APPLIED', 'PREVIOUS_PURCHASES', 'PAYMENT_METHOD',
       'FREQUENCY_OF_PURCHASES', 'AGE_GROUP', 'PURCHASE_FREQUENCY'],
      dtype='object')

In [ ]:
df.columns

Index(['CUSTOMER_ID', 'AGE', 'GENDER', 'ITEM_PURCHASED', 'CATEGORY',
       'PURCHASE_AMOUNT', 'LOCATION', 'SIZE', 'COLOR', 'SEASON',
       'REVIEW_RATING', 'SUBSCRIPTION_STATUS', 'SHIPPING_TYPE',
       'DISCOUNT_APPLIED', 'PREVIOUS_PURCHASES', 'PAYMENT_METHOD',
       'FREQUENCY_OF_PURCHASES', 'AGE_GROUP', 'PURCHASE_FREQUENCY'],
      dtype='object')

In [ ]:
import numpy as np

In [ ]:
df['Estimated_Total_Spend'] = df['PURCHASE_AMOUNT'] * (df['PREVIOUS_PURCHASES'] + 1)

In [ ]:
df[['AGE', 'AGE_GROUP', 'FREQUENCY_OF_PURCHASES', 'PURCHASE_FREQUENCY','Estimated_Total_Spend']].head(11)

,AGE,AGE_GROUP,FREQUENCY_OF_PURCHASES,PURCHASE_FREQUENCY,Estimated_Total_Spend
0,55,Mid-age,Fortnightly,14,795
1,19,Young,Fortnightly,14,192
2,50,Mid-age,Weekly,7,1752
3,21,Young,Weekly,7,4500
4,45,Mid-age,Annually,365,1568
5,46,Mid-age,Weekly,7,300
6,63,Old,Quarterly,90,4250
7,27,Young,Weekly,7,680
8,26,Young,Annually,365,873
9,57,Mid-age,Quarterly,90,155
10,53,Mid-age,Bi-Weekly,14,918

In [ ]:
binary_cols = ['SUBSCRIPTION_STATUS', 'DISCOUNT_APPLIED',]
for col in binary_cols:
    df[col] = df[col].apply(lambda x: 1 if str(x).strip().lower() == 'yes' else 0)

In [ ]:
df['Churn_Risk'] = np.where((df['REVIEW_RATING'] < 3.0) & (df['SUBSCRIPTION_STATUS'] == 0), 1, 0)

In [ ]:
df[['AGE', 'AGE_GROUP', 'FREQUENCY_OF_PURCHASES', 'PURCHASE_FREQUENCY','Estimated_Total_Spend' ,'Churn_Risk','SUBSCRIPTION_STATUS', 'DISCOUNT_APPLIED']].head(11)

,AGE,AGE_GROUP,FREQUENCY_OF_PURCHASES,PURCHASE_FREQUENCY,Estimated_Total_Spend,Churn_Risk,SUBSCRIPTION_STATUS,DISCOUNT_APPLIED
0,55,Mid-age,Fortnightly,14,795,0,1,1
1,19,Young,Fortnightly,14,192,0,1,1
2,50,Mid-age,Weekly,7,1752,0,1,1
3,21,Young,Weekly,7,4500,0,1,1
4,45,Mid-age,Annually,365,1568,0,1,1
5,46,Mid-age,Weekly,7,300,0,1,1
6,63,Old,Quarterly,90,4250,0,1,1
7,27,Young,Weekly,7,680,0,1,1
8,26,Young,Annually,365,873,0,1,1
9,57,Mid-age,Quarterly,90,155,0,1,1
10,53,Mid-age,Bi-Weekly,14,918,0,1,1